# Generated by Django 5.2.5 on 2026-02-28 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('begin', models.DateField()),
                ('end', models.DateField()),
                ('frequency', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='TodoInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('state', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DateCheckInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('task_done', models.ManyToManyField(to='TestModel.taskinfo')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('task_finish_number', models.IntegerField(default=0)),
                ('todo_finish_number', models.IntegerField(default=0)),
                ('tasks', models.ManyToManyField(related_name='tasks', to='TestModel.taskinfo')),
                ('todos', models.ManyToManyField(related_name='todos', to='TestModel.todoinfo')),
            ],
        ),
    ]
