# Generated by Django 5.2.5 on 2026-03-01 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('npc_id', models.IntegerField(default=0, verbose_name='NPC ID')),
                ('npc_name', models.CharField(default='', max_length=50, verbose_name='NPC Name')),
                ('message_type', models.IntegerField(choices=[('user', '用户消息'), ('npc', 'NPC消息')], max_length=10, verbose_name='Message Type')),
                ('content', models.TextField(verbose_name='消息内存')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='发送时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestModel.userinfo')),
            ],
        ),
    ]
