# Generated by Django 5.2.5 on 2026-03-01 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0002_chatmessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='time',
            new_name='timestamp',
        ),
    ]
