# Generated by Django 5.2.5 on 2026-03-01 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0003_rename_time_chatmessage_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='message_type',
            field=models.CharField(choices=[('user', '用户消息'), ('npc', 'NPC消息')], max_length=10, verbose_name='Message Type'),
        ),
    ]
